### ISSUE TITLE
The Docker image is not up to date

### ISSUE THREAD

**Issue by CLOVIS-AI** [binsec/binsec#12]
The https://hub.docker.com/u/binsec images are not up-to-date (according to GitHub, the latest release is 0.4.1).

**Comment by recoules** [comment]
Thank you for this report. The docker image is now up-to-date.
```console
$ docker pull binsec/binsec
```

**Comment by CLOVIS-AI** [comment]
Thanks for the update.

While waiting for the update, I built my own image, using [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) to reduce the size of the resulting image.

```Dockerfile
#region Compile Binsec

FROM archlinux:base-devel AS builder

RUN yes | pacman -Syuu --needed git make opam dune rsync gcc patch diffutils

# we're already in a container, so no need for sandboxing
RUN opam init --yes --disable-sandboxing
RUN opam install --yes ocamlgraph zarith menhir dune-site

COPY . binsec
RUN cd binsec && eval $(opam env) && make -j8 install

#endregion
#region Create the final image

FROM archlinux:base

RUN yes | pacman -Syuu

COPY --from=builder /binsec /opt/binsec
ENTRYPOINT [ "/opt/binsec/_build/install/default/bin/binsec" ]

#endregion
```

I'm not familiar with Ocaml packaging (Opam/Dune), so I guess it can be reduced further, at the moment it includes the whole repository. I saw that the `_build/install/default/lib` directory contains symbolic links to `/opt/binsec`, I'm not sure what is safe to remove or not.

Here's the size comparison:
```bash
$ docker images
binsec-arch               archlinux    6435751c5b27   2 minutes ago    524MB
binsec/binsec             latest       1daee8475b98   8 hours ago      2.72GB
binsec/binsec-0.3         latest       9fa757377882   23 months ago    4.05GB
```

**Comment by CLOVIS-AI** [comment]
As an added bonus, here is the above image adapted specifically to run the first SSE example, with everything needed:

```Dockerfile
#region Compile Binsec

FROM archlinux:base-devel AS builder

RUN yes | pacman -Syuu --needed git make opam dune rsync gcc patch diffutils

# we're already in a container
RUN opam init --yes --disable-sandboxing
RUN opam install --yes ocamlgraph zarith menhir dune-site

COPY . binsec
RUN cd binsec && eval $(opam env) && make -j8 install

#endregion
#region Create the final image

FROM archlinux:base

RUN yes | pacman -Syuu

COPY --from=builder /binsec /opt/binsec
RUN ln -s /opt/binsec/_build/install/default/bin/binsec /usr/bin/binsec
WORKDIR /opt/binsec

#endregion
#region SSE Tutorial 1

# For this example, we need Z3, as well as multiple tools from binutils (strings, objdump, readelf)
RUN yes | pacman -S --needed file binutils z3
WORKDIR examples/sse/quickstart

#endregion
```

**Comment by recoules** [comment]
Thank you @CLOVIS-AI.  
`binsec` is compiled statically so there is no much things to carry on from on layer to another.

The only requirements are shared library for `gmp` and `libc++` and the content of the `shared` directory (this part is actually tricky as it is needed to update the final path in the `binsec` binary).

You will find different versions of the docker now:
- `0.4.1` contains `binsec`, the examples and some utilities (`objdump`, `radare`, etc.);
- `0.4.1-tuto-extra` contains the same as above + `ghidra` and some other dependencies to fully replay the tuto/experimenting on your own;
- `0.4.1-dev` contains the full material to rebuild `binsec`.

**Comment by CLOVIS-AI** [comment]
Thanks a lot for your help and this tool :)
