### ISSUE TITLE
The Makefile prints incorrect error messages

### ISSUE THREAD

**Issue by CLOVIS-AI** [binsec/binsec#13]
The `which` command used in the Makefile (https://github.com/binsec/binsec/blob/master/Makefile#L24) is not available by default on all distributions. When it isn't available, the Makefile crashes with the message "Please install opam.", even if opam is installed.

Please see https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then.

**Comment by recoules** [comment]
Thank you for the information, we have changed `which` for `command -v`.
