### ISSUE TITLE
No SMT solver found

### ISSUE THREAD

**Issue by DQP2375** [binsec/binsec#18]
Hello developers I am using binsec to Automatically find opaque predicates but I get the following error

dqp@ubuntu:~/binsec$ binsec -ghidra-cache ghidra.log -bbsse-process-all-jumps echo
[smt:fatal] No SMT solver found.
Fatal error: exception Failure("abort")

But I checked to see if ocaml-bitwuzla was already installed 

dqp@ubuntu:~/binsec$ opam list
# Packages matching: installed
# Name              # Installed # Synopsis
astring             0.8.5       Alternative String module for OCaml
base                v0.14.3     Full standard library replacement for OCaml
base-bigarray       base
base-bytes          base        Bytes library distributed with the OCaml compiler
base-threads        base
base-unix           base
**bitwuzla            1.0.3       SMT solver for AUFBVFP
bitwuzla-c          1.0.3       SMT solver for AUFBVFP (C API)**
camlp-streams       5.0.1       The Stream and Genlex libraries for use with Camlp4 and Camlp5
cmdliner            1.1.1       Declarative definition of command line interfaces for OCaml
conf-emacs          1           Virtual package to install the Emacs editor
conf-g++            1.0         Virtual package relying on the g++ compiler (for C++)
conf-gcc            1.0         Virtual package relying on the gcc compiler (for C)
conf-git            1.1         Virtual package relying on git
conf-gmp            4           Virtual package relying on a GMP lib system installation
conf-ncurses        1           Virtual package relying on ncurses
conf-pkg-config     2           Check if pkg-config is installed and create an opam switch local pkgconfig folder
cppo                1.6.9       Code preprocessor like cpp for OCaml
csexp               1.5.1       Parsing and printing of S-expressions in Canonical form
curses              1.0.10      Bindings to ncurses
dot-merlin-reader   4.5         Reads config files for merlin
dune                3.5.0       Fast, portable, and opinionated build system
dune-build-info     3.5.0       Embed build informations inside executable
dune-configurator   3.5.0       Helper library for gathering system configuration
dune-private-libs   3.5.0       Private libraries of Dune
dune-site           3.5.0       Embed locations informations inside executable and libraries
dyn                 3.5.0       Dynamic type
either              1.0.0       Compatibility Either module
fix                 20220121    Algorithmic building blocks for memoization, recursion, and more
fmt                 0.9.0       OCaml Format pretty-printer combinators
fpath               0.7.3       File system paths for OCaml
ISO8601             0.2.6       ISO 8601 and RFC 3999 date parsing for OCaml
menhir              20211128    An LR(1) parser generator
menhirLib           20211128    Runtime support library for parsers generated by Menhir
menhirSdk           20211128    Compile-time library for auxiliary tools related to Menhir
merlin              3.8.0       Editor helper, provides completion, typing and source browsing in Vim and Emacs
ocaml               4.09.1      The OCaml compiler (virtual package)
ocaml-base-compiler 4.09.1      Official release 4.09.1
ocaml-config        1           OCaml Switch Configuration
ocaml-version       3.5.0       Manipulate, parse and generate OCaml compiler version strings
ocamlbuild          0.14.2      OCamlbuild is a build system with builtin rules to easily build most OCaml projects
ocamlfind           1.9.5       A library manager for OCaml
ocamlformat         0.23.0      Auto-formatter for OCaml code
ocamlgraph          2.0.0       A generic graph library for OCaml
ocp-indent          1.8.1       A simple tool to indent OCaml programs
odoc                2.1.1       OCaml documentation generator
odoc-parser         1.0.1       Parser for ocaml documentation comments
ordering            3.5.0       Element ordering
ounit2              2.2.6       OUnit testing framework
pp                  1.1.2       Pretty-printing library
qcheck              0.20        Compatibility package for qcheck
qcheck-core         0.20        Core qcheck library
qcheck-ounit        0.20        OUnit backend for qcheck
re                  1.10.4      RE is a regular expression library for OCaml
result              1.5         Compatibility Result module
seq                 base        Compatibility package for OCaml's standard iterator type starting from 4.07.
sexplib0            v0.14.0     Library containing the definition of S-expressions and some base converters
stdio               v0.14.0     Standard IO library for OCaml
stdlib-shims        0.3.0       Backport some of the new stdlib features to older compiler
stdune              3.5.0       Dune's unstable standard library
toml                7.0.0       Library for TOML with a parser, a serializer and a printer
topkg               1.0.6       The transitory OCaml software packager
tuareg              3.0.1       OCaml mode for GNU Emacs
tyxml               4.5.0       A library for building correct HTML and SVG documents
unisim_archisec     0.0.3       UNISIM-VP DBA decoder
user-setup          0.7         Helper for the configuration of editors for the use of OCaml tools
uucp                15.0.0      Unicode character properties for OCaml
uuseg               15.0.0      Unicode text segmentation for OCaml
uutf                1.0.3       Non-blocking streaming Unicode codec for OCaml
yojson              2.0.2       Yojson is an optimized parsing and printing library for the JSON format
zarith              1.12        Implements arithmetic and logical operations over arbitrary-precision integers

I don't know what the problem is, I hope I can get your help！！

**Comment by recoules** [comment]
Hi @DQP2375,

I can see that you have installed `bitwuzla` from `opam`.
Yet, I think you have built `binsec` from sources since it is not listed in the packages.
Could you try to clean and rebuild `binsec` to see if the error is still present?

```console
dune clean
dune build @install
dune install
```

Regards,
Frédéric

**Comment by recoules** [comment]
Your version actually matches.

> conflicts "llvm" {< "6.0.0"} "llvm" {>= "13.0.0"} "bitwuzla" {< "1.0.1"}

It means that `binsec` will not work with `bitwuzla` if it is lower than `1.0.1`.
 `1.0.3` is greater than `1.0.1`.

Did you try to run the command I gave you?

**Comment by recoules** [comment]
You're welcome.
Have a nice day
