### ISSUE TITLE
How to set the sse-depth to be infinite when run elational symbolic execution of constant time check?

### ISSUE THREAD

**Issue by Luweicai** [binsec/binsec#24]
As the titile. 
And is their other limited option need to be set as infinited If I want to get the example be proved constant time?

**Comment by Luweicai** [comment]
This example seems limited by the `the maximal depth`, I run it with the maxinum depth `binsec -sse -checkct -sse-depth 1000 -sse-script checkct.cfg -fml-solver-timeout 0 donna`. The result is 
```
[sse:warning] Cut path 1 (max depth) @ 0x0804d58f
[sse:info] Empty path worklist: halting ...
[sse:info] SMT queries
             Preprocessing simplifications
               total          660
               sat            32
               unsat          625
               constant enum  3

             Satisfiability queries
               total          0
               sat            0
               unsat          0
               unknown        0
               time           0.00
               average        -nan

           Exploration
             total paths                      1
             completed/cut paths              0
             pending paths                    0
             stale paths                      1
             failed assertions                0
             branching points                 36
             max path depth                   1004
             visited instructions (unrolled)  1004
             visited instructions (static)    714


[checkct:result] Program status is : unknown (0.056)
[checkct:info] 0 visited path covering 714 instructions
[checkct:info] 36 / 36 control flow checks pass
[checkct:info] 805 / 805 memory access checks pass
[checkct:warning] Exploration is incomplete:
                  - 1 paths have reached the maximal depth and have been cut (-sse-depth)
```

**Comment by Luweicai** [comment]
Seem works with depth 1000000. How to set it to be the infinity?

**Comment by recoules** [comment]
Hi @Luweicai,

Regarding your initial demand:
- `-fml-solver-timeout` is the same
- `-relse-timeout` is now `-sse-timeout`
- `-sse-depth 0` is not working but giving big enough number (e.g. 4611686018427387903) will actually do the same
- `-sse-memory` everything inside could be added to the sse script
- `-sse-load-ro-sections` & `-sse-load-sections` can be added in the sse script (e.g. `load sections .text, .rodata, .data, .got.plt, .plt from file`)
- `-relse-stat-file` could be replaced by `-checkct-stats-file`
- `-fml-solver` is now `-smt-solver`
- `-relse-leak-info` is now `-checkct-leak-info`
Others do not have meaning.

**Comment by Luweicai** [comment]
Hi, @recoules, quite thank you for you reply.
