### ISSUE TITLE
 Is binsec_v0.2 compatibale with IDASEC ?

### ISSUE THREAD

**Issue by APlus123** [binsec/binsec#3]
Hi,
Much appreciated to your awesome project.  Is binsec_v0.2 compatibale with IDASEC ? More simple guide will be greatly helpfull.

**Comment by rbonichon** [comment]
Version 0.2 should not have changed the behavior of the analyses accessible through IDASEC. 
Basically, this should work as for the previous version.

A word of caution: be aware that we are not maintaining IDASEC (neither is Robin David anymore, its initiator and main contributor), so it may break in any release. In particular, it means we will not publish a user manual for IDASEC.
