### ISSUE TITLE
Sim2 doesn't accept function name as entrypoint

### ISSUE THREAD

**Issue by AcousGit** [binsec/binsec#4]
Hi,

I wrote a simple code to test sim2 module based on the examples given in the docker. Unlike when using sse, sim2 doesn't accept function name as entrypoint.

```
$ unzip testSim.zip
$ cd testSim
$ binsec -config ./config/default.ini 
Fatal error: exception Failure("Bitvector.of_string : should start with [+-]?0[xb]")
```
 
Here is the zip file: [testSim.zip](https://github.com/binsec/binsec/files/3377915/testSim.zip)

If I replace `foo` by its address `0x560` it works well.

Thanks

**Comment by rbonichon** [comment]
This is issue is fixed in version 0.3.
