### ISSUE TITLE
Printing help requires specifying an ISA

### ISSUE THREAD

**Issue by Lesly-Ann** [binsec/binsec#49]
With version 0.9.1, running `binsec --help` without specifying the ISA gives the following error message:
```
Fatal error: exception Dynlink.Error (Dynlink.Library's_module_initializers_failed "Failure(\"Machine ISA set to unknown. Aborting. Did you forget to set an -isa switch on the command line ?\")")
```

If I add the `-isa` option it works as expected, but I can only imagine that this is a bug. I would expect the behavior to give the help without needing to specify an isa (same for -version option).

**Comment by recoules** [comment]
Dear @Lesly-Ann,

Thank you for reaching us. I was not able to reproduce this issue on my local setup. 
Is it possible that one of your plugins uses the `Kernel_options.Machine` module at top level ? One of the features of the `-help` command is that it loads all the available plugins while most of the time, they are only loaded on demand.

Regards,
Frédéric

**Comment by Lesly-Ann** [comment]
Hi Frédéric,

Indeed, you are right, my apologies for the noise!
