### ISSUE TITLE
Add Rizin/Cutter support

### ISSUE THREAD

**Issue by XVilka** [binsec/binsec#6]
I noticed you have a plugin for IDA, but it is not the only one tool available.
[Radare2](https://github.com/radareorg/radare2) is a highly-portable cross-platform reverse engineering framework and a toolkit without dependencies.  It has support for analyzing binaries, disassembling code, debugging programs, attaching to remote GDB/LLDB, WinDbg servers, rich plugin system (see `r2pm`), and integration with various decompilers. For example, ghidra decompiler plugin - [r2ghidra-dec](https://github.com/radareorg/r2ghidra-dec). It is actively developed and can be easily integrated in various open source and commercial products. I believe, it will be highly beneficial to support these and provide a package for install from `r2pm`, see the package repository here: https://github.com/radareorg/radare2-pm

In case if you need to get the information from radare2 into the OCaml you can use the so called *r2pipe* mechanism that returns JSON-formed output for the radare2 commands. We maintain a [r2pipe opam package](https://opam.ocaml.org/packages/radare2/). Feel free to reach me if you have the question or suggestions for this r2pipe interface (or radare2 in general). 

![image](https://user-images.githubusercontent.com/203261/68269641-7ae24e00-0095-11ea-95f2-cebbc7246954.png)

For documentation on writing plugins for radare2 see [Scripting](https://radare.gitbooks.io/radare2book/content/scripting/intro.html) and [Plugins](https://radare.gitbooks.io/radare2book/content/plugins/intro.html) Radare2 Book chapters.

[Cutter](https://cutter.re/) is a crossplatform Qt/C++ GUI frontend to radare2:

![image](https://user-images.githubusercontent.com/203261/68269343-78332900-0094-11ea-8646-f6226cb6043f.png)

For documentation on writing plugins for Cutter see [the official tutorial](https://cutter.re/docs/plugins.html) and the [curated list](https://github.com/radareorg/cutter-plugins) of various popular plugins.

**Comment by rbonichon** [comment]
Thanks for the detailed comment & proposal for help ! 

We know and appreciate radare2. Our main bottleneck at that point is the number of developers so that such projects become tractable. We'll look into that, even though there's no guarantee it will ever come to something.

**Comment by recoules** [comment]
Hi @XVilka, sorry for not giving any news.
We still have a manpower issue at this time and we have not yet started to explore any GUI stuff, but if you mind, we can keep the issue open.
As @rbonichon said, we know and appreciate `radare`/`rizin` and, speaking for myself, I am willing to push in that direction if the opportunity arises.
Regards
