### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by aruncgowda** [binsec/binsec#9]
@rbonichon  @strongcourage 

i have already installed ocamlfind but its giving me error please provide me the steps to install

arun@arun:~/binsec-master$ opam install ocamlfind
[NOTE] Package ocamlfind is already installed (current version is 1.8.0).
arun@arun:~/binsec-master$ ./configure
checking for make... make
checking GNU make version... Good! (4.1)
checking for ocamlfind... no
configure: error: Could not find ocamlfind

**Comment by strongcourage** [comment]
Hi,
Could you try to run the following command, then continue your installation?
~~~
eval `opam config env`
~~~
Best.

**Comment by aruncgowda** [comment]
@strongcourage 

i am getting the same error but i have installed ocamlfind

**Comment by aruncgowda** [comment]
i installed it thank you @strongcourage
